# Competition configuration options
options:
  insert_models_over_bins: false
  insert_models_over_stations: false
  enable_robot_camera: true

agv_infos:
  agv1:
    location: as1
    products:
      part_0:
        type: assembly_battery_blue
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, '-pi/4']
  agv2:
    location: as1
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
  agv3:
    location: ks3
  agv4:
    location: ks4    
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 # information on health for kitting robot
    assembly_robot_health: 1 # information on health for assembly robot
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]

models_over_bins:
   bin2:
     models:
       assembly_battery_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 1
         num_models_y: 2
   bin8:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 1

# models_over_stations:
#   as1:
#     models:
#       assembly_battery_green:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 0]
#       # assembly_pump_red:
#       #   xyz: [0.032085, -0.152835, 0.15]
#       #   rpy: [0, 0, 0]
#   as2:
#     models:
#       assembly_battery_blue:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 0]
#   as3:
#     models:
#       assembly_pump_blue:
#         xyz: [0.032085, -0.152835, 0.25]
#         rpy: [0, 0, 0]
 
# belt_models:
#   assembly_pump_blue:
#     1.0:
#       pose:
#         xyz: [0.0, 4.3, 0.92]
#         rpy: [0, 0, 'pi/2']
#   assembly_battery_red:
#     2.0:
#       pose:
#         xyz: [0.0, 4.3, 0.92]
#         rpy: [0, 0, 'pi/2']

time_limit: -1
