# Competition configuration options
options:
  insert_models_over_bins: false
  insert_models_over_stations: false
  # belt_population_cycles: 1
  enable_robot_camera: true

agv_infos:
  agv1:
    location: as2
    products:
      part_0:
        type: assembly_battery_blue
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, '-pi/4']
  agv2:
    location: ks2
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
  agv3:
    location: ks3
  agv4:
    location: ks4   
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 # information on health for kitting robot
    assembly_robot_health: 1 # information on health for assembly robot
    # deactivate this robot during kitting after placing 1 product in agv2
    disable_kitting_robot: [kitting,agv2,1] # ALWAYS this order: kitting/assembly. agv#/as#, mumber of products
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv2]
      destinations: [as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
  order_1:
    priority: 1 # default is 1 if omitted, we could omit this line
    kitting_robot_health: 1 # information on health for kitting robot
    assembly_robot_health: 1 # information on health for assembly robot
    announcement_condition: agv_station_reached
    announcement_condition_value: agv2_at_as1
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]

          
models_over_bins:
   bin1:
     models:
       assembly_regulator_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin2:
     models:
       assembly_battery_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2


models_over_stations:
  as2:
    models:
      assembly_battery_blue:
        xyz: [-0.032465, 0.174845, 0.15]
        rpy: [0, 0, 0]
  
time_limit: -1

faulty_products:
  - assembly_pump_blue_5
